source 'http://gitlab.*********.com/WP/Mobile/IOS/Specs.git'#易车私有库

platform :ios, '8.0'

target 'BPFlutter_Example' do
  pod 'BPFlutter', :path => '../../'

  target 'BPFlutter_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] ='NO'
        end
    end
end
